catalog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'), 
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name= 'my-borrowed'),
    path('loanedbooks/', views.LonedBooksListView.as_view(), name='Loned-books'),
    path('book/<uuid:pk>/renew/',views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),    

]


 # pk = primary key
 # ^ = start with  (in our case , start with book\ (^book\))
 # $ = end with   
 # ?P = named Groupe (<NAME> :Name in the name of the group)
 # atfter the <> in the Group itself 
 # (e.g \d mean degits and + mean one or many times)"""

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import os
urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
""" we added this Static url  to 
BE ABLE TO SPECIFY WHERE THE FILES 
ARE LOCATED WHEN BILDING THE TEMPLATES"""

catalog/models.py
from math import perm
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date 

# Create your models here.

# ///////////////////////////////////////////////////////////
# //   a Record is an Instance of a Model (entiter)        //
# //   each Model have a banch of fields                   // 
# //   as a result each Record have a banch of fields      //
# ///////////////////////////////////////////////////////////


class Genre (models.Model):
    """Model representing a book Genre. """
    name = models.CharField(max_length=200, help_text= "Enter a book genre (e.g sience Fiction)", verbose_name="Name of Genre")

    def __str__(self):
        """string representing the Modelobject. """
        return self.name

class Language (models.Model):
    name= models.CharField(max_length=100, help_text="Enter the language (e.g. Arabic, English) etc..")

    def __str__(self):
        return self.name

class Book (models.Model):
    """Model representing a book (but not a spesific copy of a book ). """
    title= models.CharField(max_length=200)


    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author= models.ForeignKey('Author', on_delete= models.SET_NULL, null=True)
        # on_delete= models.SET_NULL mean you can delete ana author without deleting the book it self
        # null = true means you can creat a book without an author

    Summary= models.TextField(max_length=9000, help_text='Enter a breaf description of the book')
    
    isbn= models.CharField("ISBN", max_length=13,unique= True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text="select a genre for this book")

    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True,  help_text="select the language for this book" )

    class Meta:   
        permissions =(("can_add_Book","Can add the book "),("can_change_book","Can change the book "),("can_delete_book","Can delete the book "))    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""

        return reverse ('book-detail', args=[str(self.id)])
    
    def get_id_update (self):
        return reverse('author-update', args=[self.id])

    def get_id_delete (self):
        return reverse('author-delete', args=[self.id])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ','.join (genre.name for genre in self.genre.all() [:3])
        
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can bre borrowed from library). """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text= 'Unique ID for this particular book across whole library' )
    book= models.ForeignKey('book', on_delete=models.RESTRICT, null=True)
    borrower= models.ForeignKey(User, on_delete= models.SET_NULL, null=True, blank=True)
 

    LOAN_STATUS = (
        ('m','Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
        )
    status= models.CharField(
        max_length=1,
        choices= LOAN_STATUS,
        blank= True,
        default='m',
        help_text='Book avoailablitty', 
    )
    imprint=models.CharField(max_length=200 )
    due_back = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"), )
    
    @property
    def is_overdue(self):
        """Determines if the book is overdue based on
        due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    def __str__(self):
        """String for representing the Model object."""
        return f'Book N°[{self.id}] - " {self.book.title} " '
        
class Author (models.Model):
    first_name= models.CharField(max_length=100)
    last_name= models.CharField(max_length=100)
    date_of_birth= models.DateField(null=True, blank=True)
    date_of_Death= models.DateField('Died', null=True, blank=True)
    
    class Meta:
        ordering= ['last_name', 'first_name']
        permissions= (("can_add_author", "Can add author"),("can_change_author", "Can change author"), ("can_delete_author", "Can delete author"))

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""

        return reverse('author-detail', args=[ str(self.id)])


    def __str__(self):
        """String for representing the Model object."""

        return f'{ self.first_name } {self.last_name}'

catalog/forms.py
import datetime
from catalog.models import BookInstance
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _ 


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date renewal in the past'))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date renewal mare than 4 weeks ahead'))
        return data

    class Meta:
        model= BookInstance 
        fields= ['due_back']
        help_texts = {'due_back':_('Enter a date beween ,now and 4 weeks(default3) :')}
        labels= {'due_back':_('Renewal date')}
        
# a function version of the form
"""class RenewBookForm(forms.Form):
    renewal_date= forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data =self.cleaned_data['renewal_date']
    
        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid renewal date in past'))
        
        # check if a date is in allowed range (+4 weeks from today).

        if data > datetime.date.today() + datetime.timedelta(weeks= 4):
            raise ValidationError(_('Invalid date renewal more than 4 weeks ahead.'))
            # Remmember to always return the cleaned data.
        return data"""

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, render
from .models import Book, BookInstance, Author
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy 
from catalog.forms import RenewBookModelForm
from django.views.generic.edit import CreateView, UpdateView,DeleteView

def index(request): 
    """view function for home page of site"""

    # Generate counts of some of the main objects
    num_books= Book.objects.count()
    num_instances= BookInstance.objects.count()

    # Available books (status = 'a')
    num_instances_available= BookInstance.objects.filter(status__exact= 'a').count()
    #count for authors
    num_author= Author.objects.count()

    # The 'all()' is implied by default.
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits']= num_visits + 1

    context={
        'num_books': num_books,
        'num_instances': num_instances,
        'num_author': num_author,
        'num_visits': num_visits,
        'num_instances_Available': num_instances_available,
    }

    """ Render the HTML template index.html 
    with the data in the context variable"""
    return render(request, 'index.html', context=context)

class BookListView (generic.ListView):
    model=Book
    paginate_by=10

    def get_context_data(self, **kwargs):
        context= super(BookListView, self).get_context_data(**kwargs)
        context['some_data']= 'this is just some data'
        return context

class BookDetailView (generic.DetailView):
    model= Book
    paginate_by=5

class AuthorListView (generic.ListView):
    model=Author
    paginate_by= 10

class AuthorDetailView (generic.DetailView):
    model= Author
    paginate_by=5

class LoanedBooksByUserListView (LoginRequiredMixin,generic.ListView):

    """Generic class-based view listing 
    books on loan to current user."""

    model= BookInstance
    template_name= 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by= 10
    def get_queryset(self): 
        return BookInstance.objects.filter(borrower= self.request.user).filter(status__exact='o').order_by('due_back')
        
class LonedBooksListView (PermissionRequiredMixin,generic.ListView):
    model= BookInstance
    permission_required= ('catalog.can_mark_returned',)
    template_name= 'catalog/bookinstance_list_borrowed_staff.html'
    paginate_by= 10 
    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@login_required
@permission_required ('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request,pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    
    # If this is a POST request then process the Form data

    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding)
        form = RenewBookModelForm(request.POST)
        
        # Check if the form is valid:
        if form.is_valid():
            book_instance.due_back= form.clean_data['renewal_date']
            book_instance.save()

            # redirect to a new URL
            return HttpResponseRedirect(reverse('Loned-books'))

          # If this is a GET (or any other method) create the default form.    
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm( initial= {'renewal_date': proposed_renewal_date})

    context={
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'catalog/renew_book_librarian.html', context)

class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    permission_required=('catalog.can_add_author',)
    fields = ['first_name','last_name', 'date_of_birth', 'date_of_Death']
    template_name= 'catalog/author_form.html'    

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    permission_required= ('catalog.can_change_author',)
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    template_name= 'catalog/author_form.html'    

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required= ('catalog.can_delete_author',)
    success_url= reverse_lazy('authors')
    template_name= 'catalog/author_confirm_delete.html'

class BookCreate(PermissionRequiredMixin,CreateView):
    model= Book
    permission_required=('catalog.can_add_Book')
    fields= ['title', 'author', 'Summary','isbn','genre','language']
    template_name="catalog/book_form.html"

class BookUpdate(PermissionRequiredMixin,UpdateView):
    model = Book
    permission_required=('catalog.can_change_book')
    fields= ['title', 'author', 'Summary','isbn','genre','language']
    template_name="catalog/book_form.html"

class BookDelete(PermissionRequiredMixin,DeleteView):
    model= Book
    permission_required= ('catalog.can_delete_book')
    success_url=('books')
    template_name="catalog/book_confirm_delete.html"


    

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Author</h1>
  <p>Are you sure you want to delete the author: {{ author }} </p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %} <title>{{ author }}</title> {% endblock %}

{% block content %}
  
  <h1><strong>{{ author }}</strong></h1>
  <p><em>({{ author.date_of_birth }} - {{ author.date_of_Deth }})</em></p>

  <h2>Books</h2>
  {% for book in author.book_set.all %}
    
    <h3>
      <a href=" {{ book.get_absolute_url }} "> {{ book.title }} {{ book.id }} </a>:
    </h3>
    <p>{{ book.Summary }}</p>
    <hr>
    
  {% endfor %}

  

{% endblock %}
<!--
    author.book_set.all
-->

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %} <title>List of Authors</title> {% endblock %}

{% block content %}
  
  <h1><strong>Authors</strong></h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
     <li>
         <a href="{{ author.get_absolute_url }}"> {{ author }} </a> 
         ({{ author.date_of_birth }} - {{ author.date_of_Death }})
     </li>
    {% endfor  %}
   </ul>
  {% else %} 
    <p>There is no Authors, We will add them as soon as they'r availeble</p>
    
  {% endif %}
  
{%endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html"%}

{% block content %}
  <h1>Delete Book</h1>
  <p>Are you sure you want to delete the book: {{ book }} </p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, Delete">
  </form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %} <title>{{ book.title }}</title> {% endblock %}

{% block content %}
  <h1>Title: {{ book.title }} </h1>

  <p><strong>Summary:</strong> {{ book.Summary }} </p>
  <p><strong>ISBN:</strong> {{ book.isbn }} </p>
  <p><strong>Language:</strong> {{ book.language }} </p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:"," }} </p>

  <div style="margin-left: 20px; margin-top: 20px;">

    <h4><em>Copies</em></h4>
    {% for copy in book.bookinstance_set.all %}

      <!-- copy = every BookInstance's record -->
      <!-- _set =  a reverse lookup class(similar to a funtion)
        variable django puts in for you. -->
      <hr>
      <p class=" {% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>

      {% if copy.status != 'a' %}
        <p><strong>Due to be returned: </strong>
          {{ copy.due_back }} 
        </p>
      {% endif %}

      <p><strong>Imprint: </strong>{{ copy.imprint }}</p>

      <p class="text-muted"><strong>Id: </strong> {{ copy.id }} </p>

    {% endfor %}

  </div>

{% endblock %}


<!-- book.genre.all|join: -->

catalog/templates/catalog/book_form.html
{% extends "base_generic.html"%}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %} 

{% block title %} <title>List of Books </title> {% endblock %}

{% block content %}
  <h1><strong>Books</strong></h1>

  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href=" {{ book.get_absolute_url }} ">{{ book.title }}</a>
        ({{ book.author }})
        {% if perms.catalog.can_change_book %}
        <button style="color: blue"><a href=" {{ book.get_id_update }} "> Update </a></button>
        {% endif %}
        {% if perms.catalog.can_delete_book %}
          <button style="color:red" ><a href=" {{ book.get_id_delete }} "> Delete </a></button>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>There are no books in the Library.</p>
  {% endif %}

  {% if perms.catalog.can_add_Book %}
    <button style="color: green" ><a href=" {% url 'book-create' %} ">Create</a></button> 
  {% endif %}

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_staff.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>All Borrowed Books</h1>

  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
          ({{ bookinst.due_back }})- {{ bookinst.borrower }}
          {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a> {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books borrowed.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/renew_book_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }} </p>
  <p {% if book_instance.is_overdue %} class=" text-danger" {% endif %} >Due date: {{ book_instance.due_back }} </p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value=" submit ">
  </form>

{% endblock %}